### ISSUE TITLE
Request: more screen types

### ISSUE THREAD

**Issue by drashna** [rianadon/Cosmos-Keyboards#25]
For oled, there are 128x64, 64x128, and 128x128 that are relatively common and supported.

Also, LCD screen support would be nice. Such as st7789, ili9431, etc.

**Comment by rianadon** [comment]
There are indeed many out there! I've been adding models based on the screens I've bought and have had time to measure.

I'm going to close this issue because adding I don't foresee myself adding screens for several more months (I instead have a lot of generator-specific changes planned). After that, whether I add more screens will come down to whether I'm going to use that specific screen in a keyboard I'm personally building, or if someone creates a pull request with a model for a new screen.
