### ISSUE TITLE
Case is cut horizontally

### ISSUE THREAD

**Issue by ngrigoriev** [rianadon/Cosmos-Keyboards#26]
I have just attempted to build a case.

URL: https://ryanis.cool/cosmos/beta#cf:ChYIBRAGWAEYBCACKNcBMM0BUAJAAEgAGgYIBhAAGABCUwgD4AEBeAPYAQEQAUgASABIAEgASABIAEgAYABoAHABGAEgASgBmAH0A6gB6AegAcgBsAEAkAGEB7gBAIABFDAAOChYCIgBAcABAMgB2ATQAYQH

First, Prusa complains about the STL errors.

![image](https://github.com/rianadon/Cosmos-Keyboards/assets/2364632/92b42e32-4fc6-4a4e-a1f5-8c3deb28f535)

Next, it appears that the model has a gap of some sort going across the entire case, parallel to the bottom, just above the connector holes:

![image](https://github.com/rianadon/Cosmos-Keyboards/assets/2364632/87aa4196-71c3-4d25-a86e-5571fe047ed1)

![image](https://github.com/rianadon/Cosmos-Keyboards/assets/2364632/ffadac6d-7448-4d41-bbf8-cea2a1aa7bfd)

**Comment by ngrigoriev** [comment]
After experimenting  a bit more, I found that setting "Wall Shrouding" parameter to any value >0 results in this. Setting it to 0 makes the case solid.

**Comment by rianadon** [comment]
It looks like this has something to do with the produced web being invalid. If I import the step file from both cases into PrusaSlicer, the webs only show up when wall shrouding is disabled. I also see when importing the STL that the lower left key in the thumb cluster turns dark green (which means the mesh is doing odd things there).

My guess is that the web curling in right here might have something to do with it.
<img width="531" alt="image" src="https://github.com/rianadon/Cosmos-Keyboards/assets/18223213/d4114ff5-bdda-4846-9fc7-76d9cb4da0e4">

My last build with both rounded sides & wall shrouding turned on ran into issues with the rounded sides clipping into the keycaps, resulting in me spending hours sanding down the walls so they no longer collide with the keycaps. You'll probably avoid that problem with shrouding of only 2mm, but it looks like a similar issue is to blame here.

**Comment by rianadon** [comment]
It does look like that little spot is the issue. I took your model through the yet-to-be-released V3 interface in order to position a rectangle / blank keycap right next to that bottom left key, and the model successfully sliced.

<img width="677" alt="image" src="https://github.com/rianadon/Cosmos-Keyboards/assets/18223213/976487f0-3579-4310-999c-f6e3a1f151ef">

<img width="527" alt="image" src="https://github.com/rianadon/Cosmos-Keyboards/assets/18223213/484ae482-7821-49c4-ad30-e049165a84cd">

I can send you the files if you'd like, but there are some bugs I've yet to fix with the ways column staggers get applied which results in the key positions being ever so slightly different from what you have.

V3 should be out and bug-free by end of June, so you could also wait until then. Cheers!

**Comment by ngrigoriev** [comment]
V3 is the main branch? If so, I can try myself.

**Comment by rianadon** [comment]
I haven't pushed the changes yet. I keep the website and the repository synced so that everyone gets new features at the same time.

I did however make the same change [in expert mode](https://ryanis.cool/cosmos/beta#expert:eJzlW9+P2jgQfuevsHjptgohCQlQTn3p3p1UnbZ76m51DyseTGLAtyFBsbPArvZ/vxknhPyAQu+qYnSrlk3GY3v8zTdjZ5n4cSQkiZeSw8WI3GYX5AN5aRGyomF4P+f+Y8QENLpGLrubJ3Ea8Gg2Io6SsUlJzcpFNzwqpL9TX8YJtJlDbH1km49UcFBurwPaRpHwE7b6FAXcZyB+6NgG2f9/XGjfb5YMRlDXhEeCJXI31B1/xsab3k50HaeRZIng0eOIyCRl2AIriQIWjMgLkfESf83jhD/HkaThiNhd1yBPMDD3s1vb9MirQQQPGOoG/IkLXFjPIH4c+fSJyw3ooRbowfggjVi2+LZMEtGuCNHKr3cfoY3CLHTGqs2AB1uPcOEIacKF/MKEHCnnEBKyaCbnI+IpxAlZ0PVfPECJbeWi9e10KphESSZ43gryexrNQrZrliySyq99uFX2L7ifxGCQTOIwZLiKZRIrYScVk46vDJ5SAT1v6qpbjLcAXoeMJjTyWUEEHyV36ByxUxdzFobKIZmDJ0AVmIeEHPwzpaFg5LX12up2yefb+99GJOtPukTO2Q47suJyjkoRm1HJnxhQRLGL0ISRZUh9FhCaynhBlXHhxkTtT5EaRs3ZpcETmhsQSScGymHqJxqmMMiKJWyEHWrEtfumZxAXP5wBfvZ6+GlbSmLjJ1yOsWfdza7davkqHv00eaIyBTuzQCzub6fXcZguIvCYZ1QbvsQroILCb0l9cKISgUkOTl0WZ0Ngi5210MQHjwCkre67dy3yjnwVbJqGZAooAlmQEYQC16dTWHRUMg91UQkRW0JYbTCyhQnibr4SJb2uLcc0zWII49DySubcz5XDIkZSgc6IyTIWHDOVmjldLllSzEw+yTcCwlpSCbqTjVLJeQ10D8g6a4TeqA2tMAqwUoTlDs8kVoGi1kLyxaiJ/oB5/lTGfABqrch9IqZXb3FV2ZxXtmOQBwvcDP/G2aWdXSruVlSrmnZxudMsTLvKFYtGRIf8yqY84lnS3nqihMfOEaA2g9w3ImD/wxhsf4DRszySh9li3ZnHUqzosp0lAxjBpyolQshPOeaJLF0DgMA1O0sQQB+xBBqDILv1wxSyAWaKfM58uK3PRlXY8MdU4Xgb3VCZ8PXVSy5uMiX78XOSdNydTJnUcfL712LkBn7VFsBs8XFzVfXs223y+0/4OBriY2uET08/fKyzwJOPWAOpVbLL3t6FkI0VNP22kpwdwZ4eEXgcQqcB4UZXCM8TpMch7DUgnGsKoa5x7DYQjDRFUFcONjPhQBMEnXoYX04mTHWFUFcWFtEyjxeowPEBrt3A9W9Ncb2c9LjQFEFdidlMj0NNELTrsX0kPTrm0IADuiYZkuuK4hEinhPFepJc8CAIWTNLPmqK7ZEseU5om4nS0BREjfl5OSBqnCqbG857PUC0Lvc4HmuKoK6HnvpGkwAwzW0m1BPVyzmLm3oCqCsrLwZAXRNjc2uxfiKA1S8umyh+7/NMx+4ZpK/JDrPUGcgjAX1GIOsbjVpac6f5RWN0j2w3ZwS3mS+7GuN4LpKe+lV8Vtjx02FyTMfTJTGe+q28RlBdQOorovPN/ujUB81zpbr9vHM1RuqH0q41PrVuS87TxaRUsxVgLRPopSIrOIsYTSaqpKzoZxQlW1l5FpZrCdiMCV1gcWe58kyNfpvwGY8OVWo5Q3PYH7qO7fYszxl6fXd/PVa1usvs9fu21R9Yg6H33rK8/dVe5T4dd2A6Q9caDOyB69m9gdvog93GtYKvjuvg33UA/M6w1qQqCvOD+U4MDqlR5QBR9j0gVM/cu28+WiVmHPF9xcShOfDQcvVLGVqGxDoJAcCpg9WUebEb8mlXGhlPdyzaBpFZ83+98rBeL6mehfaUHyr5noLJqnxbX4mliqVJ/12R3fEc7DVyMCkU8hOpmr+SmHfZJbOtfSALfSvb5D57b9Ulnd5h8pf1+v3D7q7RBpKNCW63B+B6y7T3Zp1SaP+Y5OxdKlq22VMVxn0t0ToZq07/cOKt6H0j2Vawb+od5ptn4nsFffzc/4eOSwDQ/sbWVVFsbj17EbQt+3QSKhaCPvy+XACtHw3gd3AQ9znHUzG8/2ucowhOYA9+zFcv1KsvL2SVvwwyxJcO5ozP5rL0/POTIK4eJfEk2cyLF469Bux1DrxJ0FQ8FcHv2IOGuGF3MpoBivufFOoo4mNCdmYq3ms6cFj/Xxxv2XoZJxIfgWgayu1bMvl7eWh1DSUU4RseI/IAevmDo4F9MiqNjdbrPz4cGZA=). It sliced without problems in prusaslicer, so hopefully will work for you. It is harder to edit things in expert mode, but what I've done is keep one tab with expert, one tab with basic/advanced, and when you make a change in basic/advanced go to expert and merge the two codes together. V3 will also add a way to take your changes in expert and convert them to basic/advanced.

**Comment by rianadon** [comment]
https://github.com/rianadon/Cosmos-Keyboards/tree/v3 is the v3 branch.
